AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wabilytics-fn

  Sample SAM Template for wabilytics-fn

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  CarrierChangedFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: wabilytics.carrierChanged.CarrierChangedFunction::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_URL: jdbc:mysql://database-1.cbfzuvbm5tmc.us-east-1.rds.amazonaws.com/reporting
          DB_USERNAME: reporting
          DB_PASSWORD: example
          DB_CREATE_TABLES: true
      Events:
        CarrierChangedFunctionReceiveMessage:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:835328222444:eventos

  AllShiftsBusyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: wabilytics.aalShiftsBusy.AllShiftsBusyFunction::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_URL: jdbc:mysql://database-1.cbfzuvbm5tmc.us-east-1.rds.amazonaws.com/reporting
          DB_USERNAME: reporting
          DB_PASSWORD: example
          DB_CREATE_TABLES: true
      Events:
        AllShiftsBusyFunctionReceiveMessage:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:835328222444:eventos

Outputs:
  CarrierChangedFunction:
    Description: "Carrier Changed Lambda Function ARN"
    Value: !GetAtt CarrierChangedFunction.Arn

  CarrierChangedIamRole:
    Description: "Implicit IAM Role created for Carrier Changed function"
    Value: !GetAtt CarrierChangedFunctionRole.Arn

  AllShiftsBusyFunction:
    Description: "All Shifts Busy Lambda Function ARN"
    Value: !GetAtt AllShiftsBusyFunction.Arn
  AllShiftsBusyFIamRole:
    Description: "Implicit IAM Role created for All Shifts Busy function"
    Value: !GetAtt AllShiftsBusyFunctionRole.Arn


