version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run echo "${qa_template}" > qa_template.yaml
      - pipenv run sam build --template-file qa_template.yaml
      - pipenv run sam package --template-file .aws-sam/build/template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1q2dzim793q9k --output-template-file qa-packaged-template.yml --s3-prefix wabilytics-app --force-upload
artifacts:
  files:
    - qa-packaged-template.yml